server:
  port: 7397

spring:
  application:
    name: itstack-demo-springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fuzhengwei/itstack-demo-config  # 换成自己的配置Git仓库的地址，如果没有可以新建工程地址，也可以克隆我的；https://github.com/fuzhengwei/itstack-demo-config
          search-paths: config-repo                               # Git仓库地址下的底层配置文件名称，如果配置多个用逗号','分割。

# 如果配置中心需要访问权限，则开启配置
# spring.cloud.config.server.git.username：Github账户
# spring.cloud.config.server.git.password：Github密码